### ISSUE TITLE
Assets support

### ISSUE THREAD

**Issue by Saleciani** [SatoshiPortal/lwk-dart#11]
Currently library only shows balance for LBTC.

Ideally wallet would display balance for tokens

Just balance and transactions for tokens should be sufficient for now, but an idea can be a seamless integration with price providers for selected tokens so we can display the balance of the tokens in other denominations.

LBTC -> displayed in CAD /EUR/USD/BRL
USDT -> Displayed in BTC/EUR/BRL
.....
Etc

This functionality can be great for building analytics in bitcoin wallets.

**Comment by i5hi** [comment]
Updated the structure to now support Assets by not locking into just L-TEST asset id.

**Comment by i5hi** [comment]
I have only tested the rust side of things. 

Would be of great help if you could update the dart test: `test/lwk_root_test.dart` to use the updated classes.
