### ISSUE TITLE
Wallet sync is not updating unspent UTXO

### ISSUE THREAD

**Issue by Saleciani** [SatoshiPortal/lwk-dart#35]
When you receive some new UTXO of a asset on a multi asset transaction the method

```
  Future<List<TxOut>> utxos({dynamic hint}) =>
      LwkCore.instance.api.walletUtxos(that: this, hint: hint);
 ```
 
 Does not update the unspent utxo via the sync wallet feature.
 
 It updates if you restart the app (or the lwk wallet)

**Comment by i5hi** [comment]
@JoaoLobo94 Are you still facing this issue?

**Comment by Saleciani** [comment]
I haven't done any check in the lastest versions of lwk.

Will test tomorrow on the latest version on iPhone to see if it still present

**Comment by Saleciani** [comment]
Tried with the latest version.

still getting the same error.

What you need to do is sign a transaction with some utxos.

Then you try again to pick some utxo and broadcast a transaction and it will give an error

<img width="494" alt="image" src="https://github.com/user-attachments/assets/d7208d12-0426-4884-af3c-9aa450234990">


I think the problem (or the lack of the update) comes from, in the sideswap case, we just upload the signed input to their server, and they publish it

as per documentation here -> https://sideswap.io/docs/#uploading-swap-inputs

so maybe that is why we currently have to restart the LWK service.

I am not totally sure how it works internally, but it is not updating the utxo in this manner, from what i understand.


Restarting the app makes it work again, but simple wallet updated do not update the utxo list 🤔

**Comment by Saleciani** [comment]
This Bug can be closed as it was resolved.

My issue was that the internal state managment of my app in some very specific cases was not trigerring the method and using a previous state for efficiency, hence using the old UTXO and triggering the error.

It is not related to state managment of rust lib
