### ISSUE TITLE
Restore wallet functionality

### ISSUE THREAD

**Issue by Saleciani** [SatoshiPortal/lwk-dart#8]
On mainnet when i try to restore a with a mnemonic that previously done transactions on other wallets it does not retrieve me all transactions, showing a blank list instead.

**Comment by Saleciani** [comment]
On further investigation it might be that only testnet L-BTC is currently supported and hardcoded as a asset, but I am not sure this is the case.

**Comment by i5hi** [comment]
Hey! Yah, currently get Transactions has hardcoded Test-LBTC


```rust

impl From<WalletTx> for Tx {
    fn from(wallet_tx: WalletTx) -> Self {
    ...
    ...
Tx {
            kind: wallet_tx.type_,
            amount: wallet_tx
                .balance
                .get(&AssetId::from_str(TLBTC_ASSET_ID).unwrap())
                .unwrap_or(&0)
                .to_owned()
                .abs() as u64,
            txid: wallet_tx.tx.txid().to_string(),
            outputs: outputs,
            fee: wallet_tx.fee,
            timestamp: wallet_tx.timestamp.unwrap(),
        }
```

The `From` trait helps us convert from the lwk WalletTx type to our own type that we bind into dart. 

You will notice this pattern a lot. 

If you want to bind a type that you want from lwk in dart, you will need to implement the `From` trait

So you end up with usage like this:

```rust

    pub fn txs(&self) -> anyhow::Result<Vec<Tx>, LwkError> {
        let txs = self
            .get_wollet()
            .transactions()?
            .iter()
            .map(|x| Tx::from(x.to_owned())) // from() enabled for Tx because we implemented `From`
            .collect();
        Ok(txs)
    }
```  
          
We have to allow the user to input AssetId so its not only adapted to Mainnet but also allows other assets to be used. 

Similar thing happens in balance, we need to upgrade it to allow any Asset, currently we only allow lbtc, lcad and usdt 

Will make this update by the end of the week.

**Comment by i5hi** [comment]
Okay, i tried a few things.
flutter_rust_bridge does not support HashMaps which is required to have a map of assetIds and balances.

Earlier we had our own struct like this:

```rust
struct Balances{
 pub lbtc: u64, 
 pub ltest: u64,
 pub lcad: u64, 
...
```

The advantage is that the end user need not bother about AssetId's when parsing balances and such a type is compatible with frb.

Disadvantage is that we would have to keep adding support for new assets.


IF we can use a HashMap, then the end user can just scan the HashMap by AssetId and find the approprioate balance.

For now we have to stick with our own `Balance` struct until frb supports HashMap unfortunately.

I will add support for LBTC (Mainnet) for now.

**Comment by i5hi** [comment]
This is what would be ideal:

```rust
pub struct AssetIdMapUInt(pub HashMap<AssetId, u64>);
pub struct AssetIdMapInt(pub HashMap<AssetId, i64>);

pub type Balances = HashMap<String, u64>;
impl From<AssetIdMapInt> for Balances {
    fn from(asset_id_map: AssetIdMapInt) -> Self {
        asset_id_map.0.into_iter()
            .map(|(key, value)| {
                let converted_value = if value < 0 { 0 } else { value as u64 };
                (key.to_string(), converted_value)
            })
            .collect()
    }
}
impl From<AssetIdMapUInt> for Balances {
    fn from(asset_id_map: AssetIdMapUInt) -> Self {
        asset_id_map.0.into_iter()
            .map(|(key, value)| (key.to_string(), value))
            .collect()
    }
}

```
Also tried with bleeding edge FRB and get the same error:

`not yet implemented: generate code for type "HashMap < String , u64 >"`

**Comment by i5hi** [comment]
https://cjycode.com/flutter_rust_bridge/guides/types/translatable/detailed/map_set

Their docs says it supports it but, not able to get it to work.

**Comment by i5hi** [comment]
HACKED!

```rust
pub type Balances = Vec<(String, u64)>;
```

This works.

**Comment by i5hi** [comment]
This should also be patched in 0.1.1 and current trunk branch

**Comment by Tecmomoa** [comment]
I'll help you fix that, so contact me immediately!

**Comment by JoaoLobo94** [comment]
> HACKED!
> 
> ```rust
> pub type Balances = Vec<(String, u64)>;
> ```
> 
> This works.

This works well in rust, but i think in flutter we cannot access the id as it is a tuple and we cannot access the value of the items without some getters 🤔
